# Generated by Django 5.1.7 on 2025-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Профессия', max_length=50, verbose_name='Профессия')),
                ('anons', models.CharField(max_length=200, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Описание профессии')),
                ('date', models.DateField(verbose_name='Дата обновления')),
            ],
        ),
    ]
